import { NextRequest, NextResponse } from 'next/server';
import Anthropic from '@anthropic-ai/sdk';

const MASTER_PROMPT = `You are helping convert tabular service design documentation into a structured service blueprint.

The source data comes from a PDF table exported from Confluence or workshop tools.

Your task is to interpret each extracted row and map it into the canonical service blueprint schema.

Do NOT invent information.
Do NOT summarize content.
Preserve original wording as much as possible.

Only classify and map.

--------------------------------------------------

Service blueprint schema

service_name
stage
stage_outcome
step
actor
user_action_event
user_need
pain_point
frontstage_touchpoint
backstage_process
system
policy_intent
business_rule
data_input
data_output

--------------------------------------------------

Row classification rules

Each extracted row must be classified as one of these:

structure_row
card_row
noise_row

structure_row:
Defines structure such as stage or step headings.

card_row:
Contains a real blueprint card such as a pain point, user need, system, or process.

noise_row:
Workshop notes, instructions, or irrelevant content.

--------------------------------------------------

Lane classification rules

For card_row records, classify content into one lane.

Use these heuristics:

User need
Statements describing what a user needs to accomplish.
Examples: "I need to understand permit requirements."

Pain point
Statements describing problems or frustrations.
Examples: "Fragmented systems create duplication."

Actor
A role or organisation performing an action.
Examples: Applicant, Border force officer.

Frontstage touchpoint
User-facing interactions such as portals, forms, phone calls.

Backstage process
Operational work behind the scenes.

System
Digital or technical systems.

Policy intent
Statements describing policy goals or regulatory purpose.

Business rule
Explicit rule governing behaviour or eligibility.

Data input
Data required for the process.

Data output
Data generated by the process.

--------------------------------------------------

Step hierarchy rules

If the row contains numbering such as:

1
1.1
1.1.1

Interpret this as step hierarchy.

Example:

1 = stage
1.1 = step
1.1.1 = substep

If the document also contains stage titles such as:

Journey part 03 – Pre movement

Then use that as the stage.

--------------------------------------------------

Multiple card rule

If a cell contains multiple items such as:

CTS-88
CTS-123
CTS-77

Split them into separate cards.

--------------------------------------------------

Metadata extraction

If the text contains tags such as:

ECITES CAN MITIGATE
BACKLOG
SELECTED FOR DEVELOPMENT

Extract these into a tags field.

--------------------------------------------------

Output format

Return JSON only.

Do not include explanation.

Each mapped row must include:

sourceRowNumber
record_type
stage
stage_outcome
step
lane_key
card_title
card_body
tags
confidence

Example output

{
  "rows": [
    {
      "sourceRowNumber": 12,
      "record_type": "card_row",
      "stage": "Pre movement",
      "stage_outcome": "",
      "step": "Apply for CITES permit",
      "lane_key": "pain_point",
      "card_title": "Inter-authority disputes cause long delays in permit approval",
      "card_body": "",
      "tags": ["CTS-88"],
      "confidence": 0.86
    }
  ]
}`;

export async function POST(req: NextRequest) {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    return NextResponse.json(
      { error: 'ANTHROPIC_API_KEY is not configured on the server.' },
      { status: 500 },
    );
  }

  let file: File | null = null;
  try {
    const formData = await req.formData();
    file = formData.get('file') as File | null;
  } catch {
    return NextResponse.json({ error: 'Invalid request body' }, { status: 400 });
  }

  if (!file) {
    return NextResponse.json({ error: 'No file provided' }, { status: 400 });
  }

  // Extract text from PDF using pdf-parse (imported via require to avoid
  // Next.js bundling its test-file side-effects at module init time)
  let pdfText = '';
  try {
    const buffer = Buffer.from(await file.arrayBuffer());
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const pdfParse = require('pdf-parse/lib/pdf-parse') as (
      buf: Buffer,
    ) => Promise<{ text: string }>;
    const { text } = await pdfParse(buffer);
    pdfText = text.trim();
  } catch (err) {
    const msg = err instanceof Error ? err.message : 'PDF parsing failed';
    return NextResponse.json({ error: `Could not read PDF: ${msg}` }, { status: 422 });
  }

  if (!pdfText) {
    return NextResponse.json(
      {
        error:
          'No text could be extracted from this PDF. It may be a scanned image — try uploading a text-based PDF.',
      },
      { status: 422 },
    );
  }

  // Send extracted text to Claude (streaming required for large max_tokens)
  let rawJson = '';
  try {
    const client = new Anthropic({ apiKey });
    const stream = client.messages.stream({
      model: 'claude-sonnet-4-6',
      max_tokens: 64000,
      messages: [
        {
          role: 'user',
          content: `${MASTER_PROMPT}\n\n--------------------------------------------------\n\nSource data:\n\n${pdfText}`,
        },
      ],
    });

    const message = await stream.finalMessage();
    const block = message.content[0];
    if (block.type !== 'text') {
      return NextResponse.json({ error: 'Unexpected response format from AI' }, { status: 500 });
    }
    rawJson = block.text;
  } catch (err) {
    const msg = err instanceof Error ? err.message : 'AI request failed';
    return NextResponse.json({ error: `AI processing failed: ${msg}` }, { status: 500 });
  }

  // Parse JSON from Claude's response (may be wrapped in a code fence)
  try {
    const jsonMatch = rawJson.match(/\{[\s\S]*\}/);
    if (!jsonMatch) throw new Error('No JSON object found in response');
    const parsed: unknown = JSON.parse(jsonMatch[0]);
    return NextResponse.json(parsed);
  } catch (err) {
    const msg = err instanceof Error ? err.message : 'JSON parse error';
    return NextResponse.json({ error: `AI returned invalid JSON: ${msg}` }, { status: 500 });
  }
}
